Remove jax.jit to fix tracing error
It appears JAX can not JIT a function where the return type is
dynamic AND it is determined through a array or tuple:

jax.errors.ConcretizationTypeError: Abstract tracer value encountered where concrete value is expected: traced array with shape float32[]
The problem arose with the `int` function. If trying to convert the data type of a value, try using `x.astype(int)` or `jnp.array(x, int)` instead.
The error occurred while tracing the function matmul at github.com/abhidg/jax-jit-static-array/.venv/lib/python3.13/site-packages/jax_jit_static_array/matmul.py:10 for jit. This concrete value was not available in Python because it depends on the value of the argument mul[0].

See https://docs.jax.dev/en/latest/errors.html#jax.errors.ConcretizationTypeError